### ISSUE TITLE
Understanding Linebuffer in Halide-HLS

### ISSUE THREAD

**Issue by amisal88** [jingpu/Halide-HLS#18]
Dear all,

I have implemented a simple windowing operation in Halide-HLS and it works fine. The pipeline code is attached below.
In the generated HLS code ("hls_target.cpp") there is an instance of linebuffer of dimensions 66 by 66 like this:
```
linebuffer<66, 66>
```
I have some questions about this linebuffer, which are:

1- Why 66 x 66 and not 64 x 64? I do not think it is the result of using Halide boundary condition, since data is streamed to the pipeline after boundary condition.

2- Why instantiating line buffer this big? Since for 3 x 3 windowing operation on a tile in streaming manner, just 3 rows (64 pixels each) of data would be sufficient to start windowing.

3- Vivado-HLS synthesis report shows that it infers 2 instances of 18Kb block RAM for the line buffer. I can not relate this amount of memory to the instantiated linebuffer. Any idea?

Thanks!

--------------------------------------------------------------------------------------------------------------------
**Attachment:**

Content of "pipeline.cpp" file:
```
#include "Halide.h"
#include <stdio.h>

using namespace Halide;

Var x("x"), y("y"), z("z"), c("c");
Var xo("xo"), yo("yo"), xi("xi"), yi("yi");


class MyPipeline {
public:
    ImageParam Input_Image;
    Param<uint16_t> hotPixelStrength;
    Func output;
    Func hw_output;
    std::vector<Argument> args;
	Func Input;
    Func sum_x;
    Func sum_xy;
    Func Conv;
	
    MyPipeline()
        : Input_Image(UInt(16), 2),
          hw_output("hw_output"),
		  output("output")
    {
    
    Input = Halide::BoundaryConditions::constant_exterior(Input_Image, 0);
     
    sum_x(x, y) = (Input(x - 1, y) + Input(x, y) + Input(x + 1, y));    
    sum_xy(x, y) =  (sum_x(x, y-1) + sum_x(x, y) + sum_x(x, y+1) - Input(x, y));
        
    Conv(x, y) =  (sum_xy(x, y)) >> 3;
        
    hw_output(x,y) = select(Input(x,y) > hotPixelStrength, Conv(x, y), Input(x,y));    
	output(x,y) = hw_output(x,y);

    // Arguments
    args = {Input_Image, hotPixelStrength};
    }


	
    void compile_cpu() {
        std::cout << "\ncompiling cpu code..." << std::endl;

        output.tile(x, y, xo, yo, xi, yi, 64, 64);
        output.compile_to_header("pipeline_native.h", args, "pipeline_native");
        output.compile_to_object("pipeline_native.o", args, "pipeline_native");
    }

    void compile_hls() {
        std::cout << "\ncompiling HLS code..." << std::endl;
		
		output.tile(x, y, xo, yo, xi, yi, 64, 64);
		hw_output.compute_at(output, xo);
		Input.compute_at(output, xo);
    	hw_output.tile(x, y, xo, yo, xi, yi, 64, 64).accelerate({Input}, xi, xo);
		
        //output.print_loop_nest();
        // Create the target for HLS simulation
        Target hls_target = get_target_from_environment();
        hls_target.set_feature(Target::CPlusPlusMangling);
        output.compile_to_lowered_stmt("pipeline_hls.ir.html", args, HTML, hls_target);
        output.compile_to_hls("pipeline_hls.cpp", args, "pipeline_hls", hls_target);
        output.compile_to_header("pipeline_hls.h", args, "pipeline_hls", hls_target);

        std::vector<Target::Feature> features({Target::Zynq});
        Target target(Target::Linux, Target::ARM, 32, features);
        output.compile_to_zynq_c("pipeline_zynq.c", args, "pipeline_zynq", target);
        output.compile_to_header("pipeline_zynq.h", args, "pipeline_zynq", target);


        output.compile_to_object("pipeline_zynq.o", args, "pipeline_zynq", target);
        output.compile_to_lowered_stmt("pipeline_zynq.ir.html", args, HTML, target);
        output.compile_to_assembly("pipeline_zynq.s", args, "pipeline_zynq", target);
    }
};

int main(int argc, char **argv) {
    MyPipeline p1;
    p1.compile_cpu();

    MyPipeline p2;
    p2.compile_hls();

    return 0;
}

```

**Comment by stevenbell** [comment]
1) It's 66x66, because the output is 64x64, and each output pixel requires a 3x3 window of input to compute.  So you need a 1-pixel boundary on all sides of the image.  The boundary conditions are computed in software, but then a 66x66 patch is passed to the hardware to produce the 64x64 output.  Does that make sense?

2) When a linebuffer is instantiated, the input and output dimensions **and** the input and output stencil sizes are specified.  The linebuffer code uses these pieces of information to allocate the right amount of memory; it's not allocating a 64x64 chunk of memory just because those are the image dimensions.  Someone else can confirm, but I think it needs to know the height of the image to reset the line buffer and/or assert a "finished" signal between images.

Someone else will have to answer (3), but my guess is that there's an extra "passthrough" linebuffer somewhere, and each linebuffer will use a whole BRAM regardless of its size.  If you implement a larger linebuffer, it won't use additional BRAMs until you exceed 18kB.

**Comment by xuanyoya** [comment]
For 1,2, @stevenbell is correct.

2. If you take a look at the code in Linebuffer.h under ../hls_support, you will find it actually only allocates a buffer with 3 rows and 66 cols. 

3. This is likely due to the memory ports issue. Since you use a window of 3x3, which means at each cycle, you need to read a column of 3 pixels out of the 2D linebuffer simultaneously. But each BRAM only has 2 ports by default, so it has to use 2 BRAMS to provide enough bandwidth for reading 3 pixels each cycle. Otherwise, the throughput will be smaller. However, like @stevenbell said you can increase your column number to fill the BRAM, so that you have better utilization of the BRAMS.

**Comment by amisal88** [comment]
@stevenbell and @xuanyoya 

For 1 @stevenbell explanation and for 3 @xuanyoya explanation totally makes sense.
But still I do not understand @xuanyoya explanation for 2. I looked at the Linebuffer.h code, but it seems that it allocates a 66 x 66 buffer. @xuanyoya can you give me more details?

Thanks!

**Comment by jeffsetter** [comment]
The template of the linebuffer being produced appears as: 
`linebuffer<66, 66>`

However, the two values in that template are the IMG_EXTENT_0 and IMG_EXTENT_1. These refer to to the image size. The buffer size that is created for this linebuffer is related to the stencil size (which is called in the code OUT_EXTENT). Note that OUT_EXTENT is found by observing the template parameters to the output_stream. The full linebuffer call for this example is:
```
 // alias the arguments                                                                                                                                                                                  
 hls::stream<AxiPackedStencil<uint16_t, 1, 1> > &_constant_exterior_1_stencil_update_stream = arg_0;
 hls::stream<AxiPackedStencil<uint16_t, 1, 1> > &_hw_output_1_stencil_stream = arg_1;
 uint16_t &_p2_hotPixelStrength = arg_2;

 hls::stream<PackedStencil<uint16_t, 3, 3> > _constant_exterior_1_stencil_stream;
#pragma HLS STREAM variable=_constant_exterior_1_stencil_stream depth=1
#pragma HLS RESOURCE variable=_constant_exterior_1_stencil_stream core=FIFO_SRL

 linebuffer<66, 66>(_constant_exterior_1_stencil_update_stream, _constant_exterior_1_stencil_stream);

```
Note that the size of _constant_exterior_1_stencil_stream, the output stencil stream, is 3x3 as expected.
